on: [push]

jobs:
  pandoc_job:
    runs-on: ubuntu-latest
    name: A job create the handbook
    steps:
      - name: Pandoc action step
        id: hello
        uses: Capycity/arduino-robot-workshop@main
      - run: "ls -la"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: README.pdf
          path: /data
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: README.pdf
